apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
      version: blue
  template:
    metadata:
      labels:
        app: django
        version: blue
    spec:
      containers:
      - name: django
        image: <current_django_image>:<tag>
        ports:
        - containerPort: 8000

